### ISSUE TITLE
Landing page

### ISSUE THREAD

**Issue by rgaiacs** [scipy-latinamerica/scipyla2017#1]
Work in Progress: http://scipyla.org/conf/2017/

Source: https://github.com/scipy-latinamerica/web_archive/tree/master/2017

**Comment by leliel12** [comment]
The project is multilanguage: https://github.com/scipy-latinamerica/web_archive/blob/master/2017/js/i18n.js

By Default i going to end in english and spanish when the project is ready i gonna ask for translations

**Comment by leliel12** [comment]
problemas: alguien puso un permanent  redirect en conf.scipyla.org (puedo haber sio yo) asi que la slucion
fue poner redirects que lleven a scipyla.org/conf/2017 pero todo funciona perfecto
