### ISSUE TITLE
Define/revise the visual identity of the conference

### ISSUE THREAD

**Issue by olemis** [scipy-latinamerica/scipyla2017#13]
Let designers do their job and tell us what needs to be done .

**Comment by rgaiacs** [comment]
@olemis do you have contact with any designer?

# To hire
- http://www.graficaliebre.com/ (for visual identity)
- http://www.cameralibre.cc/ (for videos)

# For volunteers
- Email http://libregraphicsmeeting.org/lgm/.
- Email https://mashaleonova.wordpress.com/ (she is involved with Fedora and could know someone from Cuba).

**Comment by olemis** [comment]
Thanks for the contacts .

**Comment by olemis** [comment]
We already have a designer ! \o/
I'll tell you more about her in the next few days :)

**Comment by xmnlab** [comment]
great :D

**Comment by olemis** [comment]
@heidygremium por favor reporta el progreso con los ficheros d la identidad en este ticket . Gracias .
