### ISSUE TITLE
Promotional videos and interviews

### ISSUE THREAD

**Issue by olemis** [scipy-latinamerica/scipyla2017#20]
Prior to the event date it'd be nice to record and release some videos and interviews advertising the activities scheduled during the lifetime of SciPy LA 2017 conference. It'd be necessary to define opening and closing clips and guidelines for transitions and (maybe) to include advertisement . The later could be an incentive for sponsorship.

Promotional videos might be recorded for:
- SciPy Latin America community members and founders
- Sponsors
- Reviewers of the academic program
- Keynote speakers
- Non-profit (e.g. Python Software Foundation) members and fellows
- Functionaries (e.g. governmental)
- Book authors attending SciPy LA 2017

**Comment by rgaiacs** [comment]
Do you plan to budget for the video processing?

**Comment by olemis** [comment]
That's the idea . This is still work in progress .
