### ISSUE TITLE
Design badges

### ISSUE THREAD

**Issue by olemis** [scipy-latinamerica/scipyla2017#21]
Badges should include (at least) the following elements :
- Conference logo and image
- Attendee Name
- <del>Photo</del> ... _-1'ed by @rgaiacs_
- (No more than two) titles (e.g. job title, project or community)
- <del>Company, institution or personal logo</del> ... _-1'ed by @rgaiacs_ 
- <del>vCard QR code</del> ... _-1'ed by @rgaiacs_
- Security / identity QR code (e.g. for controlling access to the venue)
- Color indicators for speakers, tutorial authors/mentors, workshop owners, sprint leaders, press, ...

**Comment by rgaiacs** [comment]
I'm -1 to the following items:
- photo,
- Company, institution or personal logo,
- vCard QR code.

**Comment by olemis** [comment]
Thanks for the feedback . I kind of agree . I'll update the list to reflect your suggestions .

**Comment by rgaiacs** [comment]
EuroSciPy organizers used https://pypi.python.org/pypi/reportlab to create the badges and certificates. You can find a tutorial at http://www.blog.pythonlibrary.org/2010/03/08/a-simple-step-by-step-reportlab-tutorial/.
