### ISSUE TITLE
Call for financial aids

### ISSUE THREAD

**Issue by olemis** [scipy-latinamerica/scipyla2017#23]
We need to think of requirements to apply and design a web form .

**Comment by olemis** [comment]
Consider [SciPy LA 2016 rules for financial aid](https://github.com/scipy-latinamerica/scipyla2016/blob/master/financial/financial_aids/rules.md) as a starting point. It is necessary to be clear about the procedures to apply for financial aid, the moment these will be approved and the moment, amounts and means for delivering the aids (moneys, flight tickets, ...).

**Comment by rgaiacs** [comment]
The link is broken.

**Comment by olemis** [comment]
I copied it from your docs . Fixed now. Thnx
