### ISSUE TITLE
Design call for academic sponsors

### ISSUE THREAD

**Issue by olemis** [scipy-latinamerica/scipyla2017#29]
Sponsorship information should be written down in a visually attractive manner . Requirements TBD ... but in advance we should figure out the value we can offer to interested academic institutions . Peer reviews might be one of them .

**Comment by rgaiacs** [comment]
@olemis what do you mean by academic sponsors? I don't know any academic institution that will sponsor one event that will take place abroad. All grants that I saw of this type involves big governmental programmes or high level cooperative agreements. Both requires more time that we have available.

For SciPyLA2016 we seek academic sponsorship very late. All grant application deadline were on October or November when we still didn't have the rooms.

If by sponsor you mean provide the venue, keep this issue open. Otherwise I would suggest to close the issue.

**Comment by olemis** [comment]
Not exactly like that ... I'm thinking of institutions that could be interested in enrolling reviewers for the academic program , which might be interested in running a certain workshop/activity or let members/employees participate on co-located (or parallel) activities prepared/organised by local peer academic institutions during the SciPy LA 2017 conf ... all that on behalf of an academic organisation , of course . Individual participations are another subject .

I've been trying to contact this side the persons who might help with higher-level coordination but still work in progress .

**Comment by olemis** [comment]
We'll have to write down the details involved in becoming an academic sponsor and the value this option might provide to prospective candidates .

**Comment by olemis** [comment]
For instance, if we accept the proposals we have discussed via the mailing list , our first academic sponsor might be the journal which is interested in providing us with access to their OJS, proceedings publication, etc ...  **for free**.

**Comment by rgaiacs** [comment]
> I'm thinking of institutions that could be interested in enrolling reviewers for the academic program,

In 2016 we call this 'Friends'. The word sponsor was reserved for (1) organisations that gave us money or (2) organisations that gave us in-kind donation such as the venue or (3) organisations that sign with us an agreement for staff time.

> which might be interested in running a certain workshop/activity

Normally companies paid for one sponsorship package to have the right to offer workshop/activity.
If someone want to run a certain workshop/activity and aren't going to pay to run it I would call them as 'Friends'.

> or let members/employees participate on co-located (or parallel) activities prepared/organised by local peer academic institutions during the SciPy LA 2017 conf ... all that on behalf of an academic organisation , of course.

This is exactly why we created the 'Friends' category.

> Individual participations are another subject .

We agree on that.

**Comment by xmnlab** [comment]
> For instance, if we accept the proposals we have discussed via the
> mailing list , our first academic sponsor might be the journal which is
> interested in providing us with access to the OJS for free.

Maybe Academic Support would sound better than Academic Sponsorship.

This just one institution was interested to become sponsor... and ask us
about about this kind of label "academc sponsor" ...

Our conference is a scientific event so, I think IMHO academic support and
sponsorship should be have more highlight.

**Comment by olemis** [comment]
> > For instance, if we accept the proposals we have discussed via the
> > mailing list , our first academic sponsor might be the journal which is
> > interested in providing us with access to the OJS for free.
> 
> Maybe Academic Support would sound better than Academic Sponsorship.

Instead of _Friends_ this category will be labeled as _Academic partners_.

**Comment by rgaiacs** [comment]
@olemis Any progress on this?
