### ISSUE TITLE
Design call for corporate sponsors

### ISSUE THREAD

**Issue by olemis** [scipy-latinamerica/scipyla2017#30]
Sponsorship information should be written down in a visually attractive manner . Requirements TBD ... but in advance we should figure out the value we can offer to interested sponsors . Advertising might be one of them (see #7 #8 #9 #10 #12 #20 #21 ).

**Comment by rgaiacs** [comment]
@olemis Any progress on this? This year we learned that we need to request sponsorship before the end of September.

**Comment by olemis** [comment]
We are still working on it . Thanks for all the reminders :)
