### ISSUE TITLE
Design call for papers

### ISSUE THREAD

**Issue by olemis** [scipy-latinamerica/scipyla2017#31]
Research a possible segmentation of prospective authors and identify lines of interest, research areas etc with proven potential and/or well-known motivation of prospective keynote speakers . Availability of reviewers with expertise on individual subject is a plus (compulsory?) . Based on this information define tracks to constrain submission scope and foster focused submissions . Plan for offering an open track to give a chance for accepting papers not complying with the scope of identified tracks.

Write down a call for papers document nailing down the value the conference can offer to prospective authors .

**Comment by olemis** [comment]
Tracks will be defined in #41 .

@heidygremium please take a look at the [Spanish CfP](https://github.com/scipy-latinamerica/scipyla2017/blob/master/docs/Call_for_Papers_ES.md) and [English CfP](https://github.com/scipy-latinamerica/scipyla2017/blob/master/docs/Call_for_Papers_EN.md) before preparing the printable version.

**Comment by olemis** [comment]
I've assigned this ticket to @xmnlab and @rgaiacs looking forward to translate CfP contents into Portuguese . This will be reverted once I find a local translator for this role .

I'd like to take advantage of this opportunity so as to figure out a possible workflow involving Transifex .

**Comment by olemis** [comment]
@sorice I applied some modifications and some other might still be necessary .

**Comment by rgaiacs** [comment]
@olemis Sorry for the late reply. I don't think that I will have time to translate the call of papers. I still need to translate SciPyLA 2016 documents from Portuguese to English. :-(

**Comment by xmnlab** [comment]
@olemis send this task request to our google groups scipyla and to scipyla
telegram group .. maybe someone will give you a hand :)
