### ISSUE TITLE
Design call for reviewers

### ISSUE THREAD

**Issue by olemis** [scipy-latinamerica/scipyla2017#32]
Based on the tracks identified during call for papers research , launch a call for international reviewers . Accepted reviewers might be interested in participating as keynote speakers . Requisites to be met by reviewers are still TBD . 

Write down a call for reviewers document nailing down the value the conference can offer to prospective reviewers .

**Comment by rgaiacs** [comment]
I got an email about the call for reviewers. Maybe we should add it to the website!
