### ISSUE TITLE
Design event flyer

### ISSUE THREAD

**Issue by olemis** [scipy-latinamerica/scipyla2017#33]
Its goal will be to be distributed to a broad audience and generate leads (so it should include links) to the sponsorship requests (e.g. #30 #29 ) as well as other calls for participation (e.g. CfP #31 , CfR #32 ).

**Comment by rgaiacs** [comment]
Need budget for print and ship.

**Comment by olemis** [comment]
Distribution may take place in digital format (e.g. pdf) . That's why I suggested inclusion of links (or QR codes when in printable form ;)

**Comment by olemis** [comment]
I'm not discarding the option of printing some to take advantage of specific advertisement opportunities though .

**Comment by xmnlab** [comment]
> Distribution may be on digital format (e.g. pdf) . That's why I suggested
> inclusion of links (or QR codes when in printable form ;)

Great, you can send that to scipyla google group and the community can
print and show that in their work/university.

**Comment by rgaiacs** [comment]
> Great, you can send that to scipyla google group and the community can
> print and show that in their work/university.

Sometimes is cheaper to print and ship. Also this helps to get the poster at an good place.
