### ISSUE TITLE
Event registration

### ISSUE THREAD

**Issue by olemis** [scipy-latinamerica/scipyla2017#34]
An automated event registration system is needed so as to control attendance . Free access vs inscription fee should be a decision to be made sooner or later. Alternately it is possible to offer free access and the purchase of merchandise advertising the event as part of the registration process .

Unconference has its own characteristics since talks are voted on and scheduled during the same day.

Satellite events should be defined through the registration system for co-located activities and social gatherings (see #15 ) .

**Comment by rgaiacs** [comment]
> An automated event registration system is needed so as to control attendance.

Eventbrite?

**Comment by olemis** [comment]
> > An automated event registration system is needed so as to control attendance.
> 
> Eventbrite?

Last time I checked it was blocked for Cuba . I'll confirm .

**Comment by olemis** [comment]
Does not seem to be working from here ... 👎
