### ISSUE TITLE
Offer for sale merchandise advertising the event / sponsors 

### ISSUE THREAD

**Issue by olemis** [scipy-latinamerica/scipyla2017#35]
A list of possible products is as follows :
- T-shirts
- (Coffee, tea, ...) cups with event logo printed on the surface
- Stickers (suggested by @rgaiacs )
- Eco bags (suggested by @rgaiacs )

Please add your own ideas .

Contact artisans and prospective sponsors interested in supporting this effort .

**Comment by rgaiacs** [comment]
Stickers!!!

**Comment by rgaiacs** [comment]
Eco bags.
