### ISSUE TITLE
Call for ambassadors

### ISSUE THREAD

**Issue by olemis** [scipy-latinamerica/scipyla2017#44]
Goals 
- Cover the Latin American countries without representation
- Gather contact info to connect Latin American communities in North America and Europe
- Look for regional (universitary , research, ...) organizations keen to help with diffusion of conference news .
- Roadmap and initial tasks for ambassadors .

**Comment by rgaiacs** [comment]
I would like to suggest that you provide some benefits for the ambassadors. For example, free ship of box with swags, discount on conference tickets (only valid if you are going to charge attendees), financial aid for tickets and accommodations, ...

**Comment by rgaiacs** [comment]
@olemis any progress?

**Comment by olemis** [comment]
@heidygremium please read the [call for Ambassadors doc](https://github.com/scipy-latinamerica/scipyla2017/blob/master/docs/Call_for_Ambassadors.md) . Based on that text we should be preparing a new presentation (high priority) and flyer (low priority) to advertise this. In the next few days I will provide you with the URL pointing at the online application form so that you can generate QR codes.

@rgaiacs @xmnlab @med-merchise please review .

@sorice please generate HTML files .
