### ISSUE TITLE
Choose partner journal

### ISSUE THREAD

**Issue by olemis** [scipy-latinamerica/scipyla2017#46]
The activities of the programme committee must be supported / complemented by
partnering with a scientific journal with previous experience on the academic
publication field. The following aspects will be considered so as to choose
one partner among all candidates :
- Journal scope and goals should be aligned or compatible with
  - the Python trademark and branding policies
  - the subjects listed in [conference tracks](https://github.com/scipy-latinamerica/scipyla2017/blob/master/organization/Tracks.md).
  - the Latin American geographical area
- Free-of-charge publication
- Provide access to an online system to manage the submissions review process
  (e.g. [Open Journal System](https://pkp.sfu.ca/ojs/) )
  - Create an specific section for the [SciPy LA 2017 conference](http://scipla.org/conf/2017)
  - ... preferably with the possibility of including conference brand and visual image.
  - Delegate (part of) section ownership to members of the conference's programmee committee 
  - Straightforward processes for author sign up and submission
  - Straightforward processes for reviewer sign up, assignment and revision
  - Straightforward processes for paper acceptance/rejection, second-round revision
    resubmission and subsequent publication of camera-ready manuscripts
- Clear definition of the minimal requirements to collaborate
  (e.g. minimal number of papers).
- Indexed by e.g. Google Scholar, ISI Web of Science, SCOPUS, ... or alike
- Impact factor, Index Copernicus Value , ... or alike

**Comment by rgaiacs** [comment]
I think this is done. I'm closing this now.
