### ISSUE TITLE
Certificate design

### ISSUE THREAD

**Issue by olemis** [scipy-latinamerica/scipyla2017#5]
Consider [SciPy LA 2016 certificate design](https://github.com/scipy-latinamerica/scipyla2016/tree/master/print_materials/certificates) as an example, and starting point.

**Comment by D3f0** [comment]
The URL is wrong. It's https://github.com/scipy-latinamerica/scipyla2016/tree/master/print_materials/certificates.
There's a horrendous script used to generate the covers for the videos at https://github.com/D3f0/scipyla_video_covrs 
lxml can be used in a more elegant way, but it works :D
I would advice to use vectors as much as possible to reduce CPU power needed to convert this SVG to PNG, PDF or whatever.

**Comment by rgaiacs** [comment]
We can use Jinja2 as template engine to generate all SVG. :-)

**Comment by olemis** [comment]
@D3f0 URL fixed . Thanks !
@rgaiacs I'll take a look into this at the right time . Details should be discussed in #22 and might have impact upon other similar printable material needed for the conference.
